### ISSUE TITLE
Serializable List not working with @FragmentArg

### ISSUE THREAD

**Issue by andersu** [excilys/androidannotations#1313]
I have a list of serializable objects List\<Leg> legs;
It is annotated with @Extra in my activity and with @FragmentArg in my fragment.

When I send this list from one activity to another via 
RouteLegsActivity_.intent(this).legs(legs).start();
it works find and the generated code is 

```java
public RouteLegsActivity_.IntentBuilder_ legs(List<Leg> legs) {
            return super.extra(LEGS_EXTRA, ((Serializable) legs));
}
```

When I try to do the same to the fragment via RouteLegsFragment_.builder().legs(legs).build()
the generated code is:

```java
public RouteLegsFragment_.FragmentBuilder_ legs(List<Leg> legs) {
            args.putSerializable(LEGS_ARG, legs);
            return this;
}
```

This does not compile because of the missing cast to Serializable.
This seems like a bug to me. Or am I doing something wrong?

**Comment by WonderCsabo** [comment]
Thanks for reporting, this is indeed a problem. We should add a cast in case of these situations.

**Comment by WonderCsabo** [comment]
@yDelouis i assigned this to you since you worked on the bundle helpers.

**Comment by yDelouis** [comment]
`List` does not extends `Serializable`, so it's normal that the code for fragment doesn't compile. What is not normal is that the annotation is validated.
In order to have a working code, the annotated field should be an `ArrayList<Leg>` or another implementation of `List<Leg>` which implement 'Serializable'.

About the `Activity` part, it shouldn't be valid because, at runtime, it could produce a `ClassCastException` if the implementation does not implement `Serializable`.

**Comment by WonderCsabo** [comment]
@yDelouis what are you suggesting then? :) Fixing the validation in order to invalidate this case?

**Comment by yDelouis** [comment]
Yes.

**Comment by WonderCsabo** [comment]
Can you fix this, then?

**Comment by yDelouis** [comment]
I'm on it !

**Comment by WonderCsabo** [comment]
This is now fixed.

**Comment by andersu** [comment]
Thanks guys :)
