### ISSUE TITLE
@SystemService & android.appwidget.AppWidgetManager

### ISSUE THREAD

**Issue by ened** [excilys/androidannotations#1377]
Given I inject the AppWidgetManager service into a Fragment like this:

```
@SystemService
protected AppWidgetManager appWidgetManager;
```

Then the generated code looks like this:
```
appWidgetManager = ((AppWidgetManager) getActivity().getSystemService(Context.APPWIDGET_SERVICE));
```

However, this will result in NPE, because AppWidgetManager can not be retrieved like that.

Instead, the following code should be generated:
```
appWidgetManager = AppWidgetManager.getInstance(getActivity());
```

**Comment by dodgex** [comment]
[`Context.APPWIDGET_SERVICE`](http://developer.android.com/reference/android/content/Context.html#APPWIDGET_SERVICE) has been added with API 21 and you probably tested on an older version. i think this issue may happen for other services too.

@yDelouis @WonderCsabo any idea? while for this special case we could just use generate the code for the "old" way of getting this service...


but what about other services? i think we should try to invalidate this use based on minSdk but with a check for [`@TargetApi`](http://developer.android.com/reference/android/annotation/TargetApi.html), as one could have code that is used depending on app version

so:
minSdk 10 but using a service available only in sdk >10: invalidate
minSdk 10 but using a service available only in sdk >10 with `@TargetApi(value > 10)`: generate code

**Comment by WonderCsabo** [comment]
@dodgex i am not sure what you mean. If one uses a system service constant which is not available in minSdkVersion, then LINT will show an error on the constant itself. I think we are not responsible if the user still wants to use that service.

**Comment by WonderCsabo** [comment]
For this special case, we can generate the `AppWidgetManager.getInstance`.

**Comment by dodgex** [comment]
@WonderCsabo yeah. i think you are right.

**Comment by WonderCsabo** [comment]
@ened can you add detail about the API level you used?

**Comment by ened** [comment]
Android 4.4 (19)

**Comment by WonderCsabo** [comment]
As @dodgex said, this constant was added in API 21, so probably that is way this returned null on 19. Can you check this on API 21?

**Comment by ened** [comment]
https://developer.android.com/reference/android/content/Context.html#getSystemService(java.lang.String) 
-> returns null for unknown services according to documentation. Should be clear without test. :-)


https://developer.android.com/reference/android/content/Context.html#APPWIDGET_SERVICE

**Comment by WonderCsabo** [comment]
@dodgex actually you still have a point, because the user do not use the constant directly, we generate it. And if does not run on the generated sources (i think that is the case), the error only will show up at runtime. So it maybe still a good idea to do what you suggested. Actually we can also check out the `@TargetApi` on the injected field.

**Comment by WonderCsabo** [comment]
For this special case we can still use the old injection. It does the same on API 21 as getSystemService(), @ened ?

**Comment by WonderCsabo** [comment]
I read all the Service constants, and a few Service classes has special case:

AppWidgetManager: see above
BluetoothAdapter: [see](http://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html)
UsageStatsManager: Constant was only added in API 22, class available since 21
WallpaperService: constant added in API 1, class available since API 7 (WTF)
BatteryManager: Constant was only added in API 21, class available since 1

The rest classes are appeared in the same API as the constant, so no minSdkVersion check is needed for them.

I would says we should implement the special cases for AppWidgetManager and BluetoothAdapter, for the rest cases we cannot really do anything (actually WallpaperService is not a problem for us).

**Comment by WonderCsabo** [comment]
My bad, BluetoothAdapter is not a special case, because we are injection a BluetoothManager actually, which has same API level as the constant. It is a shame that the doc is still incorrect...

**Comment by ened** [comment]
When I inject UsageStatsManager by constant name on API 21, will it work, though?

**Comment by WonderCsabo** [comment]
I do not think so, because the constant is only available since API 22 (at least the doc says that). But you can try it.
