### ISSUE TITLE
Support for Context Menus

### ISSUE THREAD

**Issue by KleinerHacker** [excilys/androidannotations#1401]
In some cases I need a support for context menus. There is a way to do this with android annotations? Like that:

<pre>
@EActivity
@ContextMenus({@ContextMenu(value = {R.menu.my_menu}, view = {R.id.my_view})})
public class MyActivity extends Activity {
    @ContextMenuItem
    protected MenuItem menuItem;

    @ContextItem
    protected void onContextItemClick() {
    }
}
</pre>

**Comment by WonderCsabo** [comment]
Currently this is not possible, but we can create such annotations and corresponding code generators.

I am not sure we could use a `@ContextMenuItem` annotation, because these items are only available when the context menu is shown, so i do not think we should store references them in the `Activity`/`Fragment`. The listener method should be able to pass the clicked item instead.

I am also thinking about this way.
```java
@RegisterContextMenu(R.menu.my_menu)
@ViewById(R.id.my_view)
View myView;
```

This is more readeble code than the long menu-view pair array. But it relies on `@ViewById` and forces the user to use that even if he/she does not want to.

BTW, i never used context menus, so i just thinking with looking at the documentation. @yDelouis @dodgex WDYT?

**Comment by KleinerHacker** [comment]
But the <pre>@ContextItem</pre> annotation for item click method is possible?

**Comment by WonderCsabo** [comment]
I think it is possible to implement. When a context menu item is clicked, the `onContextItemSelected()` menu is invoked in the `Fragment/Activity` and a `MenuItem` is passed, just like with options menu.

**Comment by KleinerHacker** [comment]
That is fine! :+1:

**Comment by WonderCsabo** [comment]
I am closing this one, because nobody voted for this. But with the new plugin system landing soon, this will be easy to implement as an AA plugin.
