### ISSUE TITLE
POST params empty after 3.3

### ISSUE THREAD

**Issue by bperin** [excilys/androidannotations#1415]
Not sure exactly whats going on, I looked at the PR briefly and couldn't pin point anything, but @POST annotated fields are not sending form data at all

```
@Rest(rootUrl = "http://test.myapi.com/v1/", converters = { GsonHttpMessageConverter.class,FormHttpMessageConverter.class})
public interface ApiClient extends RestClientErrorHandling {

	@Post("users/login")
    LoginResponse login(LinkedMultiValueMap<String, String> data);

}

```

is a simplified version of my rest client but simple changing the AA version in build.gradle from 3.3 (or 3.3.1) to 3.2 it works.

**Comment by dodgex** [comment]
are you using spring-android 1.x or 2.x? if 1.x have you tried the latest 2.x milestone? As of 3.3 there is support for 2.x maybe this broke 1.x support in this case.

**Comment by bperin** [comment]
Spring-android 2.0.0-SNAPSHOT & 2.0.0-M1 both fail with AA 3.3+ but work on 3.2

**Comment by dodgex** [comment]
weird... well i'm not using spring-android in my projects :/

**Comment by WonderCsabo** [comment]
@bperin actually your code was never correct. You are defining `GsonHttpMessageConverter` first and `FormHttpMessageConverter` second. Both converters can handle `LinkedMultiValueMap<String, String>`, this means the first converter, `GsonHttpMessageConverter` will take precedence, hence you will create a json request.

Why it was working in AA 3.2? Well, AA 3.2 does not have support for RestTemplate 2.x, and calls it in a wrong way, but this was your luck. AA creates the `RestTemplate` instance by calling the no-arg constructor. This constructor was changed in Spring 2.x from 1.x:

1.x the no-arg constructor **does not add** the default converters
2.x the no-arg constructor **adds the default** converters

To fix this problem, we clear the converters list since AA 3.3, and add the ones defined in the `@Rest` annotation. So only your converters are used.
In AA 3.2, the no-arg constructor first adds the default converter list, does not clear it, and then adds your list from the annotation. So this is where you were lucky: in the [default list](https://github.com/spring-projects/spring-android/blob/43c3e7c4441d7ac6f971b9da45cc7614e508a7f0/spring-android-rest-template/src/main/java/org/springframework/web/client/RestTemplate.java#L786), `FormHttpMessageConverter` is before `GsonHttpMessageConverter`, that is why a form-data content type request is created.

**Comment by bperin** [comment]
@WonderCsabo thanks for replying,
When you say the no arg constructor are you referring to not adding the converters to the @Rest interface?

**Comment by bperin** [comment]
Also I can confirm re-arranging the converters works

**Comment by WonderCsabo** [comment]
I was referring to the no-arg constructor of the `RestTemplate` class.
