### ISSUE TITLE
Make Singleton beans thread safe

### ISSUE THREAD

**Issue by guitcastro** [excilys/androidannotations#1421]
Here is the implementation of a Singleton bean:

```java
private static Foo_ instance_;
public static Foo_ getInstance_(Context context) {
    if (instance_ == null) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
        instance_ = new Foo_(context.getApplicationContext());
        instance_.init_();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }
    return instance_;
}
```

The generated code should be thread safe, so the getInstance_ method should be synchronized:
```java
private static Foo_ instance_;
public static synchronized  Foo_ getInstance_(Context context) {
    if (instance_ == null) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
        instance_ = new Foo_(context.getApplicationContext());
        instance_.init_();
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }
    return instance_;
}
```

**Comment by WonderCsabo** [comment]
I am not sure this is needed. All bean injections happen in the main thread, so these never will be executed concurrently. Of course the client can call `getInstance_()` manually, but that is not really needed and not too clean. In those cases, the client should take care of synchronization, otherwise it is not needed and only adds an unnecessary performance setback.

**Comment by WonderCsabo** [comment]
No answer since a week, i am closing this ticket. Feel free to reopen if you have anything to add.
