### ISSUE TITLE
Plugin model availability

### ISSUE THREAD

**Issue by n0k** [excilys/androidannotations#1460]
Hi, 

I've read that a plugin model for creating custom annotations will be available for version 4.0 I was wondering approximately by when would it be available?

Thanks!

**Comment by WonderCsabo** [comment]
There is no ETA unfortunately. We plan to merge all the features which are ready, then freeze the project until the plugin architecture is not done, because that changes a lot of things. You can check out the proof of concept implementation here https://github.com/yDelouis/androidannotations/commits/957_plugins. 

BTW these kind of questions better fit to the mailing list. http://groups.google.com/group/androidannotations
