### ISSUE TITLE
Do not force Fragment#setHasOptionsMenu(boolean) when using @OptionsMenu with a Fragment

### ISSUE THREAD

**Issue by feugatos** [excilys/androidannotations#1468]
Hi there,

I'm using AndroidAnnotations 3.3.1. 

Recently I encountered a use case where I wanted to display or hide the options menu based on the incoming Intent action.

More specifically I'm using a custom FragmentPagerAdapter where based on the constructor arguments I call setHasOptionsMenu(boolean) to either true or false inside FragmentPagerAdapter#getItem(int).

When it comes to Fragments, using the @OptionsMenu annotation forces setHasOptionsMenu(boolean) to true inside init_(Bundle).

```java
private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        Resources resources_ = getActivity().getResources();
        ...
        --> setHasOptionsMenu(true); <--
        restoreSavedInstanceState_(savedInstanceState);
        ...
}
```

Thus my solution of setting setHasOptionsMenu(boolean) inside FragmentPagerAdapter#getItem(int) doesn't work.

I'd like to suggest the following enhancement.

Add an extra parameter to the @OptionsMenu annotation whose default value would keep the existing behavior of setting/forcing setHasOptionsMenu(boolean) to true for Fragments, but when explicitly set, let the user/programmer have to manually call setHasOptionsMenu(boolean) in order to decide whether to display the options menu or not.

This extra parameter would be applicable only to Fragments, as Activity/AppCompatActivity doesn't have a method similar to setHasOptionsMenu() that I know of.

Thanks in advance.

eg. My workaround for the time being is override Fragment#onCreateOptionsMenu() to inflate the menu and set setHasOptionsMenu(boolean) in my FragmentPagerAdapter.

**Comment by WonderCsabo** [comment]
This is a valid request, however, you should remember that AA always supports the common use-case and generates code for it. If you need dynamic behavior, maybe it is not the best idea to use static (compile-time) annotations for it. I am not sure we want to add that flag. But this is only my oppinion, @yDelouis @dodgex WDYT?

I can offer two workarounds though, where you can still use the generated inflation:

First:
```java
@AfterInject
void afterInject() {
  setHasOptionsMenu(false);
}
```
This will be called after `init_` calls `setHasOptionsMenu(true)`, so basically it will just leave it on `false`, and you can change it to `true` programatically when needed.

Second:

In a base `Fragment`, create two methods:

```java
void enableOptionsMenu(boolean enable) {
  super.setHasOptionsMenu(enable);
}

@Override
void setHasOptionsMenu(boolean hasMenu) {
  // empty
}
```

And call `enableOptionsMenu` in your adapter instead of `setHasOptionsMenu`.

**Comment by yDelouis** [comment]
I agree with @WonderCsabo. We can't provide a solution for each specific use cases. The project would be too complicated (and we don't have time).
The workarounds provided by @WonderCsabo seems enough to me.
