### ISSUE TITLE
@Background on @EBean - Protected changed to Public

### ISSUE THREAD

**Issue by KleinerHacker** [excilys/androidannotations#1493]
Hi @all,

if I mark a protected method in an @EBean as @Background the view level for this method is changed from protected to public. If you need to call the Bean directly (like MyBean_.getInstance_(context)) the hidden methods are viewable and usable now!

**Comment by WonderCsabo** [comment]
Hi!

Actually this is the case for [all overridden classes with AA](https://github.com/excilys/androidannotations/blob/develop/AndroidAnnotations/androidannotations/src/main/java/org/androidannotations/helper/APTCodeModelHelper.java#L197). I do not think this is a big deal, since basically you should never reference the generated classes. If you need to create the bean manually with `MyBean_.getInstance_(context)` (which should be avoided), you can still save the bean like this:
```java
MyBean bean = MyBean_.getInstance_(context);
```
Then use you will only see your classes. When you reference `bean`.

This issue can be fixed easily, though, so i am marking this as an enhancement.
