### ISSUE TITLE
Two injections with the same name results with NPE

### ISSUE THREAD

**Issue by NoiseDoll** [excilys/androidannotations#1530]
If you have two classes
Class 1.
``` Java
@EActivity
public class Test1 extends Activity {
  @Bean
  Class a;
}
```
Class 2:
``` Java
@EActivity
public class Test2 extends Test1 {
  @Bean
  Class a;
}
```

Then in Test2_ you will get something like this:
``` Java
private void init_{
  a = Class_.getInstance_(this);
  a = Class_.getInstance_(this);
}
```
And a will be null

**Comment by dodgex** [comment]
i think you mean that `Test1.this.a` is null. this is caused as `Test2.this.a` hides the field in `Test1`... i'm not sure if there is a way to set the `a` inside of `Test1` from `Test2_` scope...

**Comment by dodgex** [comment]
i did some [tests](https://gist.github.com/dodgex/d7978105c011a8efb074)... it would be possible to correctly set the `a` field for both classes...

by doing
```java
private void init_{
    ((Test1) this).a = Class_.getInstance_(this);
    ((Test2) this).a = Class_.getInstance_(this);
}
```

but i'm not sure if we want to support that... as shadowing a field is kind of bad practice

@WonderCsabo @yDelouis ?

**Comment by NoiseDoll** [comment]
I'm just removing injecting from child Class and then it works from both classes.
But you can forget to remove injections in child classes after some refactoring and be surprised why value is null.

**Comment by dodgex** [comment]
@NoiseDoll good that this simple change works for you. refactoring can always surprise you with unexpected NullPointerExceptions. thats not a direct AndroidAnnotations issue.

the question if we want to support injecting fields with the same (shadowed) name in two classes is still present, as it could happen that one has a snipped like this:

```java
@EActivity
public class Test1 extends Activity {
  @Bean
  BeanA a;
}

@EActivity
public class Test2 extends Test1 {
  @Bean
  AnotherBeanA a;
}
```

the issue i see is that it might make the generated code less readable due to the casts as (afaik) we can not test if we need the cast or not.

**Comment by WonderCsabo** [comment]
I think we should not change AA b because of this (bad) use case. Please
use a work around.
