### ISSUE TITLE
Consider to move to the new gradle Transform API

### ISSUE THREAD

**Issue by guitcastro** [excilys/androidannotations#1644]
Note, I'm not demand anything, but maybe worth the effort to remove the dependence from android-apt and use the new [Transform API](http://tools.android.com/tech-docs/new-build-system/transform-api).

**Comment by dodgex** [comment]
this would require to rewrite the whole project as the transformation api and APT are two totaly diffrent ways to do stuff.

while we generate new java sources that get compiled, the transform api allows to MODIFY compiled class files. not sure if we want that

**Comment by WonderCsabo** [comment]
Thanks for the suggestion!

@dodgex beat me with his answer.

I agree that this may come with several benefits, but...

First of all, we would have to completely rewrite the implementation of AA. This is not what we want in general, since this project already lacks the needed resources in constrast to it numbers of users and the large feature set. Currently all developers and external contributors are working on their limited spare time on the project.

Secondly, as @dodgex explained, this method changes classes and not generates new ones (it seems?). This project philosophy is to do not include any magic. Everything what is generated can be clearly observed by the client. This input classes are not changed, this also allows seamless debugging.

At last, the Java Annotation processing is a standard, it is used by lots of tools, which tools can actually work together (the Transform API does not really support that). Java Annotation processing is build system independent, everything can use it by invoking `javac`.

**Comment by WonderCsabo** [comment]
Since we will not do it in near future, i am closing this ticket.
