### ISSUE TITLE
@Pref in @EBean value lost 

### ISSUE THREAD

**Issue by NodensN** [excilys/androidannotations#1648]
I don't know why but, when I call myPref.xxxxx.get(); in @ EBean I get the default value whereas this same value was updated just few minute before like this myPref.edit().xxxxx.put("hello world").apply();

Any ideas as to why it wouldn't be in sync?

**Comment by WonderCsabo** [comment]
Are you sure you are working on the same editor? What is the `SharedPref.Scope` you are using?

**Comment by NodensN** [comment]
My interface is like this : 
```java
@SharedPref
public interface MyPrefs {
  @DefaultRes(value = R.string.default, keyRes = R.string.xxxxx)
    String xxxxx();
...
}
```
But this issue just happens randomly once in a while on a EBean, most of the time it's working.

**Comment by WonderCsabo** [comment]
You are using the default *scope*, which is `Scope.ACTIVITY`. This will use the current `Activity`'s name as the shared preferences name. So if you are setting the value in an `FirstActivity`, then getting a value in another `SecondActivity`, you will not see the value, since they will use different shared preferences. Maybe this is your case. To fix this, you can use `Scope.UNIQUE` or `SCOPE.APPLICATION_DEFAULT`.

**Comment by NodensN** [comment]
That is the problem, I use this EBean in the same ```Activity``` my ```MainActivity```, any idea?

**Comment by WonderCsabo** [comment]
I have no idea, it should work. I suggest to debug it.

**Comment by NodensN** [comment]
Yes it should. Thanks anyway.

**Comment by WonderCsabo** [comment]
@NodensN any update on this one?

**Comment by WonderCsabo** [comment]
Closing due to lack of answer.
