### ISSUE TITLE
Generate switch statement instead of anonymous functions for listeners.

### ISSUE THREAD

**Issue by AlmogBaku** [excilys/androidannotations#1649]
For improving performance, instead of generating an anonymous class listener(HardReference), make the generated class implements the listener interface, and do a switch in order to send to the right method(http://stackoverflow.com/a/1504365/1405814).

**Comment by WonderCsabo** [comment]
While this would gain some improvements because no anonymous classes are generated, it would also add complexity, and really complicate the generation code also. So sorry, but we will not change this.

**Comment by AlmogBaku** [comment]
@WonderCsabo is that mean that you won't even consider it as a PR or for future releases?

**Comment by WonderCsabo** [comment]
Well, i am not sure about this one. ButterKnife and such also uses anonymous classes. I think we would need a really detailed performance benchmark, and if that proves the current architecture is performing much worse, then it maybe it worths the time to change it. Otherwise i do not think so. However creating such benchmark would require lots of work and knowledge.

@dodgex @yDelouis WDYT?

**Comment by AlmogBaku** [comment]
@WonderCsabo why is that so complex?, instead of generating blocks, we need to generate switch case, and to add "implements".. that's it.
