### ISSUE TITLE
@Receiver.Extra of type Intent is not considered as a Parcelable extra of the broadcast Intent

### ISSUE THREAD

**Issue by tlevavasseur-innovantic** [excilys/androidannotations#1717]
```
@Receiver(actions = "BROADCAST_NETWORK_ERROR", local = true)
protected void onNetworkError(@Receiver.Extra("EXTRA_RETRY_INTENT") Intent retry) {
```
will consider the Intent param "retry" as the broadcast intent and not the "EXTRA_RETRY_INTENT" Parcelable extra of the broadcast intent.

Doing this don't solve the issue : 
```
@Receiver(actions = "BROADCAST_NETWORK_ERROR", local = true)
protected void onNetworkError(Intent broadcast, @Receiver.Extra("EXTRA_RETRY_INTENT") Intent retry) {
```
and the broadcast intent is passed as param twice.

**Comment by WonderCsabo** [comment]
Yeah, this is an edge case. Please note the `@Receiver.Extra` annotation is only a marker, so you can pass the key as a String. But otherwise the behaviour is just the same without using those annotations.

This is problematic, because currently we the parameters of type `Intent` as the original `Intent`. This is because in 99% of the cases an `Intent` is not used as an extra, and if people adding an `Intent` parameter, they expect the original `Intent`.

We could say that if the `Intent` parameter is marked with the `@Extra` annotation, then we interpret it as an extra, however this would break the consistency between the annotated and not annotated usage, and also complicate our generation code.

@dodgex @yDelouis any thoughts?

**Comment by dodgex** [comment]
I think this should be a doable fix.

**Comment by WonderCsabo** [comment]
@dodgex so do you mean if the `Intent` param has extra annotation, then it is considered as an extra, otherwise the origianal `Intent`?

**Comment by dodgex** [comment]
yeah.

**Comment by WonderCsabo** [comment]
It turned out `@OnActivityResult` already has this behaviour. I will change `@Receiver` and `@ReceiverAction`.

**Comment by WonderCsabo** [comment]
@tlevavasseur-innovantic done!
