### ISSUE TITLE
OnViewChangedNotifier possible memory leak

### ISSUE THREAD

**Issue by mniami** [excilys/androidannotations#1745]
Hi guys, 

I can see in my class that OnViewChangedNotifier could cause memory leak. 
registerOnViewChangedListener() method is called in any EBean class with parameter "this" but never unregister.
That's for me serious memory issue. 

```java
public static OnViewChangedNotifier replaceNotifier(OnViewChangedNotifier notifier) {
		OnViewChangedNotifier previousNotifier = currentNotifier;
		currentNotifier = notifier;
		return previousNotifier;
	}
public static void registerOnViewChangedListener(OnViewChangedListener listener) {
		if (currentNotifier != null) {
			currentNotifier.listeners.add(listener);
		}
	}
```
My proposition is to add sth like that
```java
public static OnViewChangedNotifier replaceNotifier(OnViewChangedNotifier notifier) {
		OnViewChangedNotifier previousNotifier = currentNotifier;
if (previousNotifier != null){ previouseNotifier.listeners.clear(); }
		currentNotifier = notifier;
		return previousNotifier;
	}
```

Please consider to change it in later version.

Best regards Damian.

**Comment by WonderCsabo** [comment]
@mniami i just checked and this is not a problem. When the `Activity` / `Fragment` is (re)created, its notifier is also reset, so the old listeners will be eligible for garbage collection.

**Comment by mniami** [comment]
@WonderCsabo actually can't find any reset method, It is replaceNotifier() called only. 
Maybe a good idea is to keep WeakReference instead, becasue not clearing listeners keeps your fragments/activities forever. That's my impression only.

**Comment by WonderCsabo** [comment]
There is no explicit reset method, but Activities objects are killed, and new ones are created at the time, when the notifier could be a problem. And a new notifier object will be created, the old one will be garbage collected.

The exception is retained / backstack Fragments, but in that case, keeping the old notifier is needed, because you have to keep the listeners as well, and new ones are not added.

Of course we could use week references, but there is no need for that. We are not keeping anything forever. Debug the code and see for yourself.

**Comment by mniami** [comment]
Ok, thanks for the explanation.
