### ISSUE TITLE
Can't find annotations within the jar

### ISSUE THREAD

**Issue by btrautmann** [excilys/androidannotations#1854]
Hi, this isn't a bug or anything but not sure how to submit a question otherwise. I currently use version 3.3.2 but want to upgrade to the latest stable release, 4.1.0 but when I try (I need to use a jar file, not the normal gradle dependency method) it seems that annotations are gone. 

You can see in this picture of my current version that they are there. 
![screen shot 2016-09-21 at 9 34 56 pm](https://cloud.githubusercontent.com/assets/8343465/18734526/480eaf58-8043-11e6-817e-725833590da0.png)

I see that 4.1.0 is more modular but I figure that normal annotations should be in the main jar. Am I missing something? Thank you.

**Comment by btrautmann** [comment]
Ok so I believe I found the correct jar at: https://www.versioneye.com/java/org.androidannotations:androidannotations-api/4.1.0

androidannotations-api-4.1.0.jar

But this seems to be a sketchy site that's not affiliated with you. It does contain the annotations I need, but is this where people should be getting the jar? The one in the maven repo does not contain these annotations.

**Comment by dodgex** [comment]
the jar on maven repository contains the files. i'm sure because i use them in my project AND i just downloaded the jar and checked the content with 7zip.

or are you searching for a specific annotation that is missing?

**Comment by btrautmann** [comment]
Ah, you're right! I think the first time I checked, I actually downloaded it from here:
https://mvnrepository.com/artifact/org.androidannotations/androidannotations/4.1.0
Which seems to be a processor and does not contain the actual annotations!

I did find the right one at
https://mvnrepository.com/artifact/org.androidannotations/androidannotations-api/4.1.0

While we're at it, what's the first JAR do though? (the processor one)

**Comment by WonderCsabo** [comment]
You should [search on Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.androidannotations%22%20v%3A%224.1.0%22), the artifacts are deployed officially there.

The processor jar is responsible for actually reading the source code and creating the generated classes. It is a separate artifact because it should not be added to the APK.

[Here](https://github.com/excilys/androidannotations/wiki/Building-Project-Gradle) you can read how you can configure your project properly.
