### ISSUE TITLE
do you plan support plugins?

### ISSUE THREAD

**Issue by hamsterksu** [excilys/androidannotations#957]
Hi,

I think some developers want to add custom annotations to "inject" custom libs, which need to handle activity lifecycle. 

So do you plan support plugins? 

My idea: plugin will provide annotations and handlers for them. Also handler should have access to "parent" holder like EActivityHolder/EFragmentHolder/etc

What do you think about it?

Thanks,
Gennadiy

**Comment by dodgex** [comment]
@yDelouis had you any time to work on this? it seems that the need for a plugin system grows from week to week.

**Comment by WonderCsabo** [comment]
@yDelouis any updates on the plugin feature?

**Comment by WonderCsabo** [comment]
@yDelouis several things came into my mind about the plugin system

#### Copying non-AA annotations

When we copy non AA annotations when subclassing and overriding methods, we now have to exclude annotations coming from the plugins from the copy. Before that we just filtered the org.androidannotations namespace, but the plugins will have a different namespace, so we have to explicitely filter those annotations as well.

#### Handler calling older

I think we should add some more intelligent logic for handler calling order, and it is crucial for plugins. For example some plugin may want to called before another handler, and after another handler etc. I think we should add two methods to `AnnotationHandler`: `shouldBeCalledBefore()` and `shouldBeCalledAfter()`. These methods can return list of annotation .class objects. The `AnnotationHandlers` class should try to satisfy all these constraints and build an ordered list.

#### Bundle

I think we should copy all org.androidannotations plugins to the bundle zip.

#### JavaDoc

Since our classes will be an API for the plugin creators, we should add some JavaDoc at least for the most interesting parts.

#### IDE/build tool

@yDelouis have you tried your implementation with all possibilities (Eclipse with no build tool, IntelliJ with no build tool, m2e, IntelliJ with Gradle, IntelliJ + Maven, others)?

**Comment by WonderCsabo** [comment]
Classes to be promoted to be API:

* `handler` package:
  * `AbstractListenerHandler` (maybe)
  * `AnnotationHandler`
  * `AnnotationHandlers` (only the `add()` method, so not sure)
  * `BaseAnnotationHandler`
  * `BaseGeneratingAnnotationHandler`
  * `HasParameterHandlers`
  * `GeneratingAnnotationHandler`

* `helper` package:
  * `AndroidConstants`
  * `AndroidManifest`
  * `AnnotationHelper`
  * `APTCodeModelHelper`
  * `BundleHelper`
  * `CanonicalNameConstants`
  * `CanonicalNameConstants`
  * `CanonicalNameConstants`
  * `CanonicalNameConstants`
  * `CanonicalNameConstants`

**Comment by yDelouis** [comment]
I prefer to promote as few classes as possible and promote them later if some plugin developers really need it.

**Comment by WonderCsabo** [comment]
I think my proposal meets that criteria. ☺

**Comment by yDelouis** [comment]
Yes, it's to explain my decisions about classes annotated with `(maybe)`.

**Comment by WonderCsabo** [comment]
This is done (except the JavaDocs...).

Issues with the plugin systems should be reported in separate tickets.

**Comment by WonderCsabo** [comment]
I just realised our CI deployment broke after we merged the plugin system branch... I fixed it now, so the latest snapshot is available from the Sonatype snapshots repo.
